<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>pusula</AssemblyName>
    <RootNamespace>Pusula</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pusula.UnitTests" />
    <InternalsVisibleTo Include="Pusula.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

</Project>
